version: '3.9'

services:
#  app:
#    image:
  adsDb:
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres

  clientsDb:
    image: postgres:16
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: postgres