// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import dev.netwid.TPO.Lab3.utils.Auth;

import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class ChromeOrderTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
//        System.setProperty("webdriver.chrome.driver", "./drivers/chromedriver");
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void order() {
        Auth.auth(driver);
        // Test name: Order
        // Step # | name | target | value
        // 1 | open | https://www.lamoda.ru/p/mp002xm005zs/clothes-blacksi-futbolka/ |
        driver.get("https://www.lamoda.ru/p/mp002xm005zs/clothes-blacksi-futbolka/");
        // 2 | setWindowSize | 1920x1032 |
        driver.manage().window().setSize(new Dimension(1920, 1032));
        // 3 | waitForElementPresent | xpath=//div[6]/div/div/div/div | 30000
        // wait modal
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[6]/div/div/div/div")));
        }
        // 4 | click | xpath=//div[6]/div/div/div/div |
        // close modal
        driver.findElement(By.xpath("//div[6]/div/div/div/div")).click();
        // 5 | click | xpath=//div[2]/div/div[3]/div/div/div/div/div[2] |
        // click choose size selector
        driver.findElement(By.xpath("//div[2]/div/div[3]/div/div/div/div/div[2]")).click();
        // 6 | click | xpath=//div[2]/div[2]/div/div/div/div[2] |
        // click M size
        driver.findElement(By.xpath("//div[2]/div[2]/div/div/div/div[2]")).click();
        // 7 | runScript | window.scrollTo(0,600) |
        js.executeScript("window.scrollTo(0,600)");
        // 8 | click | xpath=//div[5]/div/div/div/div/div/button/span |
        // click add to cart
        driver.findElement(By.xpath("//div[5]/div/div/div/div/div/button/span")).click();
        // 11 | waitForElementPresent | xpath=//div[6]/div/div/div[4]/a | 30000
        // wait go to cart
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[6]/div/div/div[4]/a")));
        }
        // 12 | click | xpath=//div[6]/div/div/div[4]/a |
        // click go to cart
        driver.findElement(By.xpath("//div[6]/div/div/div[4]/a")).click();
        // 13 | waitForElementPresent | xpath=//div[4]/div/button/span | 30000
        // wait go to order
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[4]/div/button/span")));
        }
        // 14 | click | xpath=//div[4]/div/button/span |
        // click go to order
        driver.findElement(By.xpath("//div[4]/div/button/span")).click();
        // 15 | waitForElementPresent | xpath=//div[4]/div[2]/div/div[2]/div/div/div/div | 30000
        // wait surname input
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[4]/div[2]/div/div[2]/div/div/div/div")));
        }
        // 16 | click | xpath=//div[4]/div[2]/div/div[2]/div/div/div/div |
        // click surname input
        driver.findElement(By.xpath("//div[4]/div[2]/div/div[2]/div/div/div/div")).click();
        // 17 | type | xpath=//div[2]/div/div/div/div[2]/input | Кузьмин
        // type surname
        driver.findElement(By.xpath("//div[2]/div/div/div/div[2]/input")).sendKeys("Кузьмин");
        // 18 | click | xpath=//div[2]/div/button |
        // click choose pick point
        driver.findElement(By.xpath("//div[2]/div/button")).click();
        // 19 | waitForElementPresent | xpath=//div/div/div/div[2]/div/div[2]/div/div/div/div/div | 30000
        // wait first pick point
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div/div/div/div[2]/div/div[2]/div/div/div/div/div")));
        }
        // 20 | click | xpath=//div/div/div/div[2]/div/div[2]/div/div/div/div/div |
        // click first pick point
        driver.findElement(By.xpath("//div/div/div/div[2]/div/div[2]/div/div/div/div/div")).click();
        // 21 | waitForElementPresent | xpath=//div[3]/button/span | 30000
        // wait pick here
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[3]/button/span")));
        }
        // 22 | click | xpath=//div[3]/button/span |
        // click pick here
        driver.findElement(By.xpath("//div[3]/button/span")).click();
        // 23 | waitForElementPresent | xpath=//span[contains(.,'Оформить заказ')] | 30000
        // wait do order
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//span[contains(.,'Оформить заказ')]")));
        }
        // 24 | waitForElementVisible | xpath=//span[contains(.,'Оформить заказ')] | 30000
        // wait do order
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//span[contains(.,'Оформить заказ')]")));
        }
        // 25 | waitForElementPresent | xpath=//span[contains(.,'Оформить заказ')] | 30000
        // wait do order
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//span[contains(.,'Оформить заказ')]")));
        }
        // 26 | waitForElementPresent | xpath=//span[contains(.,'Оформить заказ')] | 30000
        // wait do order
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//span[contains(.,'Оформить заказ')]")));
        }
        // 27 | click | xpath=//span[contains(.,'Оформить заказ')] |
        // click do order
        driver.findElement(By.xpath("//span[contains(.,'Оформить заказ')]")).click();
        // 28 | waitForElementPresent | xpath=//main/div/div/div/div[3]/a | 30000
        // wait go to orders
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//main/div/div/div/div[3]/a")));
        }
        // 29 | click | xpath=//main/div/div/div/div[3]/a |
        // click go to orders
        driver.findElement(By.xpath("//main/div/div/div/div[3]/a")).click();
        // 30 | assertText | xpath=//div[2]/div[4]/span | 1 090 ₽
        // assert cost
        assertThat(driver.findElement(By.xpath("//div[2]/div[4]/span")).getText(), is("1 090 ₽"));
    }
}
