// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import dev.netwid.TPO.Lab3.utils.Auth;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;

import java.util.*;

public class ChromeSearchTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
//        System.setProperty("webdriver.chrome.driver", "./drivers/chromedriver");
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void search() {
        Auth.auth(driver);
        // Test name: Search
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://www.lamoda.ru/");
        // 2 | setWindowSize | 1920x1032 |
        driver.manage().window().setSize(new Dimension(1920, 1032));
        // 3 | click | xpath=//input |
        // click search input
        driver.findElement(By.xpath("//input")).click();
        // 4 | type | xpath=//input | 123
        // type 123 in search
        driver.findElement(By.xpath("//input")).sendKeys("123");
        // 5 | sendKeys | xpath=//input | ${KEY_ENTER}
        // ENTER
        driver.findElement(By.xpath("//input")).sendKeys(Keys.ENTER);
        // 6 | waitForElementPresent | xpath=//div[2]/div/div/div/div/div/div/div/div/div[2]/div | 30000
        // wait sorting selector
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[2]/div/div/div/div/div/div/div/div/div[2]/div")));
        }
        // 7 | click | xpath=//div[2]/div/div/div/div/div/div/div/div/div[2]/div |
        // click sorting selector
        driver.findElement(By.xpath("//div[2]/div/div/div/div/div/div/div/div/div[2]/div")).click();
        // 8 | click | xpath=//div[3]/div/div/span |
        // choose sorting price descending
        driver.findElement(By.xpath("//div[3]/div/div/span")).click();
        // 9 | click | xpath=//div[2]/div/div/div/div/a |
        // click category
        driver.findElement(By.xpath("//div[2]/div/div/div/div/a")).click();
        // 10 | runScript | window.scrollTo(0,452) |
        js.executeScript("window.scrollTo(0,452)");
        // 11 | mouseOver | xpath=//a/div/div/div/div |
        // mouse over card
        {
            WebElement element = driver.findElement(By.xpath("//a/div/div/div/div"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        // 12 | click | xpath=//a/div/div/div/div |
        // click card
        driver.findElement(By.xpath("//a/div/div/div/div")).click();
        // 13 | runScript | window.scrollTo(0,0) |
        js.executeScript("window.scrollTo(0,0)");
        // 14 | waitForElementPresent | xpath=//h1/a/span | 30000
        // wait text
        {
            WebDriverWait wait = new WebDriverWait(driver, 30000);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//h1/a/span")));
        }
        // 15 | assertText | xpath=//h1/a/span | Lacoste
        // assert text lacoste
        assertThat(driver.findElement(By.xpath("//h1/a/span")).getText(), is("Lacoste"));
    }
}
