// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import dev.netwid.TPO.Lab3.utils.Auth;

import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class GeckoLogoutTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
//        System.setProperty("webdriver.gecko.driver", "./drivers/geckodriver");
        WebDriverManager.firefoxdriver().setup();
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void logout() {
        Auth.auth(driver);
        // Test name: Log out
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://www.lamoda.ru//");
        // 2 | setWindowSize | 1936x1048 |
        driver.manage().window().setSize(new Dimension(1936, 1048));
        // 3 | open | https://www.lamoda.ru/customer/account/logout/ |
        driver.get("https://www.lamoda.ru/customer/account/logout/");
        // 4 | assertElementPresent | xpath=//button[contains(.,'Войти')] |
        {
            List<WebElement> elements = driver.findElements(By.xpath("//button[contains(.,\'Войти\')]"));
            assert (elements.size() > 0);
        }
    }
}
