// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import dev.netwid.TPO.Lab3.utils.Auth;

import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class GeckoAddAndDeleteFromCartTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
//        System.setProperty("webdriver.gecko.driver", "./drivers/geckodriver");
        WebDriverManager.firefoxdriver().setup();
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void addAndDeleteFromCart() {
        Auth.auth(driver);
        // Test name: AddAndDeleteFromCart
        // Step # | name | target | value
        // 1 | open | https://www.lamoda.ru/p/mp002xm005zs/clothes-blacksi-futbolka/ |
        driver.get("https://www.lamoda.ru/p/mp002xm005zs/clothes-blacksi-futbolka/");
        // 2 | setWindowSize | 1920x1032 |
        driver.manage().window().setSize(new Dimension(1920, 1032));
        // 3 | waitForElementPresent | xpath=//div[8]/div/div/div/div | 30000
        // wait modal
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[6]/div[2]/div/div[1]/div")));
        }
        // 4 | click | css=.icon_cross-thin-white |
        // close modal
        driver.findElement(By.xpath("//div[6]/div[2]/div/div[1]/div")).click();

        driver.findElement(By.xpath("//div[6]/div/div/div[1]/div")).click();

        // 5 | click | xpath=//div[2]/div/div[3]/div/div/div/div/div[2] |
        // click choose size
        driver.findElement(By.xpath("//div[2]/div/div[3]/div/div/div/div/div[2]")).click();
        // 6 | click | xpath=//div[2]/div[2]/div/div/div/div[2] |
        // choose size
        driver.findElement(By.xpath("//div[2]/div[2]/div/div/div/div[2]")).click();
        // 7 | runScript | window.scrollTo(0,600) |
        js.executeScript("window.scrollTo(0,600)");
        // // 8 | click | xpath=//div[5]/div/div/div/div/div[2]/div |
        // // add in favs
        // driver.findElement(By.xpath("//div[5]/div/div/div/div/div[2]/div")).click();
        // 9 | click | xpath=//span[contains(.,'Добавить в корзину')] |
        driver.findElement(By.xpath("//span[contains(.,\'Добавить в корзину\')]")).click();
        // 10 | mouseOver | xpath=//div[5]/div/div/div/div/div/button |
        {
            WebElement element = driver.findElement(By.xpath("//div[5]/div/div/div/div/div/button"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        // 11 | mouseOut | xpath=//div[5]/div/div/div/div/div/button |
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        // 12 | click | xpath=//div[6]/div/div/div[4]/a |
        // click go to cart button
        driver.findElement(By.xpath("//div[6]/div/div/div[4]/a")).click();
        // 13 | waitForElementPresent | xpath=//span[contains(.,'Перейти к оформлению')] | 30000
        // wait remove from cart button
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//span[contains(.,\'Перейти к оформлению\')]")));
        }
        // 14 | click | xpath=//button/span |
        // click remove from cart button
        driver.findElement(By.xpath("//button/span")).click();
        // 15 | waitForElementPresent | xpath=//button[contains(.,'В избранное')] | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//button[contains(.,\'В избранное\')]")));
        }
        // 16 | click | xpath=//div[3]/div/button[2] |
        // click remove from cart button
        driver.findElement(By.xpath("//div[3]/div/button[2]")).click();
        // 17 | waitForElementPresent | xpath=//a[contains(.,'Перейти в каталог')] | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//button[contains(.,\'Перейти в каталог\')]")));
        }
        // 18 | assertText | xpath=//div[4]/div/div[2]/div | В корзине нет товаров
        assertThat(driver.findElement(By.xpath("//div[4]/div/div[2]/div")).getText(), is("В корзине нет товаров"));
    }
}
