// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import dev.netwid.TPO.Lab3.utils.Auth;

import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class GeckoSearchTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
//        System.setProperty("webdriver.gecko.driver", "./drivers/geckodriver");
        WebDriverManager.firefoxdriver().setup();
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void search() {
        Auth.auth(driver);
        // Test name: Search
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://www.lamoda.ru//");
        // 2 | setWindowSize | 1920x1032 |
        driver.manage().window().setSize(new Dimension(1920, 1932));
        // /html/body/div[6]/div/div/div[1]/div

        // 3 | waitForElementPresent | xpath=//div[8]/div/div/div/div | 30000
        // wait modal
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[6]/div/div/div[1]/div")));
        }
        // 4 | click | css=.icon_cross-thin-white |
        // close modal
        driver.findElement(By.xpath("//div[6]/div/div/div[1]/div")).click();


        // 3 | click | xpath=//input |
        // click search input
        driver.findElement(By.xpath("//div[1]/div/header/div[3]/div/div/div/div/input")).click();
        // 4 | type | xpath=//input | 123
        // type 123 in search
        driver.findElement(By.xpath("//div[1]/div/header/div[3]/div/div/div/div/input")).sendKeys("123");
        // 5 | click | xpath=//button/div |
        // click search button
        driver.findElement(By.xpath("//div[1]/div/header/div[3]/div/div/div/div/button")).click();
        // 6 | waitForElementPresent | xpath=//div[2]/div/div/div/div/div/div/div/div/div[2]/div | 30000
        // wait sorting selector
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[2]/div/div/div/div/div/div/div/div/div[2]/div")));
        }
        // 7 | click | xpath=//div[2]/div/div/div/div/div/div/div/div/div[2]/div |
        // click sorting selector
        driver.findElement(By.xpath("//div[2]/div/div/div/div/div/div/div/div/div[2]/div")).click();
        // 8 | click | xpath=//div[3]/div/div/span |
        // choose sorting price descending
        driver.findElement(By.xpath("//div[3]/div/div/span")).click();
        // 9 | click | xpath=//div[2]/div/div/div/div/a |
        // click category
        driver.findElement(By.xpath("//div[2]/div/div/div/div/a")).click();


        // 15 | assertText | xpath=//h1/a/span | Lacoste
        // assert text lacoste
        assertThat(driver.findElement(By.xpath("//div[2]/div[2]/div/div/div/div/div/div[2]/div")).getText(), is("Emporio Armani"));
    }
}
