// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class GeckoLoginTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
//        System.setProperty("webdriver.gecko.driver", "./drivers/geckodriver");
        WebDriverManager.firefoxdriver().setup();
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void login() {
        // Test name: Log in
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://www.lamoda.ru//");
        // 2 | setWindowSize | 1936x1048 |
        driver.manage().window().setSize(new Dimension(1936, 1048));
        // 3 | click | xpath=//button |
        // click Войти button
        driver.findElement(By.xpath("//button")).click();
        // 4 | waitForElementPresent | xpath=//form/div[2]/div/div/div/div | 30000
        // wait email field
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//form/div[2]/div/div/div/div")));
        }
        // 5 | click | xpath=//form/div[2]/div/div/div/div |
        // click email field
        driver.findElement(By.xpath("//form/div[2]/div/div/div/div")).click();
        // 6 | click | xpath=//div[2]/div/div/div/div/div[2]/input |
        // click email input
        driver.findElement(By.xpath("//div[2]/div/div/div/div/div[2]/input")).click();
        // 7 | type | xpath=//div[2]/div/div/div/div/div[2]/input | rotile3904@facais.com
        // type in email input
        driver.findElement(By.xpath("//div[2]/div/div/div/div/div[2]/input")).sendKeys("rotile3904@facais.com");
        // 8 | click | xpath=//form/div[3]/div/div/div |
        // click password field
        driver.findElement(By.xpath("//form/div[3]/div/div/div")).click();
        // 9 | click | xpath=//div[3]/div/div/div/div/div[2]/input |
        // click password input
        driver.findElement(By.xpath("//div[3]/div/div/div/div/div[2]/input")).click();
        // 10 | type | xpath=//div[3]/div/div/div/div/div[2]/input | tf%zRv4dQ)-WWB-
        // type password
        driver.findElement(By.xpath("//div[3]/div/div/div/div/div[2]/input")).sendKeys("tf%zRv4dQ)-WWB-");
        // 11 | click | xpath=//div[5]/button |
        // click Войти button
        driver.findElement(By.xpath("//div[5]/button")).click();
        // 12 | waitForElementPresent | xpath=//a[contains(.,'Профиль')] | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//a[contains(.,\'Профиль\')]")));
        }
    }
}
